theme: light

identity_validation:
  reset_password:
    jwt_secret: ${JWT_SECRET}

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: "192.168.0.4"
      policy: one_factor

session:
  name: authelia_session
  secret: ${SESSION_SECRET}
  expiration: 1h
  cookies:
    - name: authelia_session
      domain: 192.168.0.4.sslip.io
      authelia_url: https://192.168.0.4.sslip.io
      default_redirection_url: https://192.168.0.4.sslip.io/

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: ${STORAGE_ENCRYPTION_KEY}

notifier:
  filesystem:
    filename: /config/notification.log

server:
  address: tcp://0.0.0.0:9091/